server_dev/community/urls.py
from django.urls import path
from . import views


app_name = 'community'

urlpatterns = [
    path('board/',views.board_list, name='board_list'),
    path('<int:board_id>/', views.board_detail, name='board_detail'),
    path('reply/create/<int:board_id>/', views.reply_create, name='reply_create'),
    path('board/create/', views.board_create, name='board_create'),
]

server_dev/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('main/', include('main.urls')),
    path('comm/', include('community.urls')),
    path('user/', include('user.urls')),
    path('mart/', include('mart.urls')),
]

server_dev/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name="index"),
    path('second/',views.second, name="second"),
    path('third/',views.third, name="third")
]

server_dev/server_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('main/', include('main.urls')),
    path('comm/', include('community.urls')),
    path('user/', include('user.urls')),
    path('mart/', include('mart.urls')),
]

server_dev/community/models.py
from django.db import models
from user.models import User


'''게시글(MainBoard) 모델'''

class MainBoard(models.Model):
    AREA_CHOICES = (
        ('20100000', '서울특별시'), ('20120000', '강남구'), ('20112000', '강동구'), ('20103000', '강북구'), ('20110000', '강서구'), ('20124000', '관악구'),
        ('20113000', '광진구'), ('20123000', '구로구'), ('20125000', '금천구'), ('20102000', '노원구'), ('20101000', '도봉구'), ('20109000', '동대문구'),
        ('20122000', '동작구'), ('20111000', '마포구'), ('20108000', '서대문구'), ('20121000', '서초구'), ('20114000', '성동구'), ('20105000', '성북구'),
        ('20119000', '송파구'), ('20118000', '양천구'), ('20116000', '영등포구'), ('20117000', '용산구'), ('20104000', '은평구'), ('20106000', '종로구'),
        ('20115000', '중구'), ('20107000', '중랑구')
    )
    area = models.CharField(max_length=8, choices=AREA_CHOICES, default='20122000')
    title = models.CharField(max_length=200, blank=False)
    content = models.TextField(max_length=1000, blank=False)
    writer = models.CharField(max_length=50)
    created_dt = models.DateTimeField(auto_now_add=True, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '커뮤니티'
        verbose_name_plural = '커뮤니티'
        db_table = 'tb_mainboard'


'''댓글(Reply) 모델'''

class Reply(models.Model):
    reply = models.TextField()
    author = models.CharField(max_length=50)
    board = models.ForeignKey('MainBoard', on_delete=models.CASCADE)
    created_dt = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.reply
    
    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = '댓글'
        db_table = 'tb_reply'

server_dev/community/forms.py
from django import forms
from .models import  MainBoard, Reply

class WriteForm(forms.ModelForm):
    class Meta:
        model = MainBoard
        fields = ['title', 'content', 'area']
        labels = {'title': '제목', 'content': '내용', 'area': '지역'}

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['reply']
        labels = {'reply': '댓글 내용'}

        
# class SearchForm(forms.ModelForm):
#     class Meta:
#         model = Search
#         fields = ['keyword']
#         labels = {'keyword': '검색키워드'}

server_dev/community/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseNotAllowed
from .models import MainBoard, Reply
from main.models import TbEntArea
from user.models import User
from django.utils import timezone
from .forms import WriteForm, ReplyForm
from django.core.paginator import Paginator
from django.db.models import Q
from user.decorators import login_required

#Create your views here.

'''게시판 목록 출력 기능'''
def board_list(request):
  all_area = TbEntArea.objects.all()                            #지역 선택
  area_text = request.GET.get('area', '20100000')
  page = request.GET.get('page', '1')                           #페이지
  kw = request.GET.get('kw', '')                                #검색어
  board_list = MainBoard.objects.order_by('-created_dt')
  if kw:
    board_list = board_list.filter(
      Q(title__icontains=kw) |                                  #제목
      Q(content__icontains=kw)                                  #내용
  ).distinct()
  if area_text != '20100000':
    board_list = board_list.filter(
      Q(area__exact=area_text)
    ).distinct()
  
  paginator = Paginator(board_list, 10)                         #한 페이지당 10개씩 출력
  page_obj = paginator.get_page(page)

  area_text = int(area_text)
  login_session = request.session.get('login_session', '')
  context = {'board_list': page_obj, 'page': page, 'kw': kw, 'area_text': area_text, 'all_area': all_area, 'login_session': login_session}
  return render(request, 'community/board.html', context)  


'''특정 게시글 클릭 시 게시글 속으로 들어가는 기능'''
@login_required
def board_detail(request, board_id):
  board = get_object_or_404(MainBoard, pk=board_id)
  login_session = request.session.get('login_session', '')
  comments = ReplyForm()
  comment_view = Reply.objects.filter(board=board_id)
  context = {'board': board, 'comments': comments, 'comment_view': comment_view, 'login_session': login_session}
  return render(request, 'community/board_detail.html', context)


'''게시글에 대한 댓글 기능'''
@login_required
def reply_create(request, board_id):
  board = get_object_or_404(MainBoard, pk=board_id)
  login_session = request.session.get('login_session', '')
  if request.method == "POST":
    form = ReplyForm(request.POST)
    if form.is_valid():
      reply = form.save(commit=False)
      reply.create_dt = timezone.now()
      reply.board = board
      reply.author = login_session
      reply.save()
      return redirect('community:board_detail', board_id=board.id)
  else:
    return HttpResponseNotAllowed('Only POST is possible.')
  context = {'board': board, 'form': form, 'login_session': login_session}
  return render(request, 'community/board_detail.html', context)
  

'''게시글 작성 기능'''
@login_required
def board_create(request):
  login_session = request.session.get('login_session', '')
  if request.method == 'POST':
    form = WriteForm(request.POST)
    if form.is_valid():
      board = MainBoard()
      board.title = form.cleaned_data['title']
      board.content = form.cleaned_data['content']
      board.area = form.cleaned_data['area']
      board.created_dt = timezone.now()
      board.writer = login_session
      board.save()
      return redirect('community:board_list')
  else:
    form = WriteForm()
  context = {'form': form, 'login_session': login_session}
  return render(request, 'community/board_write.html', context)

server_dev/templates/community/board.html
{% extends 'base.html' %}
{% load community_filter %}
{% block content %}
<!-- Mashead header-->
<section class="py-10 bg-white">
    <div class="container px-5 px-lg-5 my-5 mt-10">
        <h3>커뮤니티</h3>
        <div class="row">
            <div class="col-sm-6">
                <div class="btn-group">
                    <button class="btn btn-danger">
                        지역선택&nbsp;&nbsp;
                            <select class="form-select-sm " id="area_filter">
                                {% for list in all_area %}
                                    {% if list.ent_area_cd == area_text %}
                                        <option value="{{ list.ent_area_cd }}" selected>{{ list.ent_area_nm }}</option>
                                    {% else %}
                                        <option value="{{ list.ent_area_cd }}">{{ list.ent_area_nm }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select> 
                    </button>
                </div>
            </div>
            <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}" placeholder="검색어를 입력하세요">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search"><i class="fa fa-search"></i></button>
                </div>
            </div>
            </div>

        </div>

        <div>
            <table class="table">
                <tbody>
                    <tr>
                        <th width="15%">번호</th>
                        <th width="15%">지역</th>
                        <th width="50%">제목</th>
                        <th width="10%">작성자</th>
                        <th width="10%">작성일시</th>
                    </tr>
                    </tr>
                    {% if board_list %}
                    {% for board in board_list %}

                            <tr>
                                <td>
                                    {{ board_list.paginator.count|sub_filter:board_list.start_index|sub_filter:forloop.counter0|add:1 }}
                                </td>
                                <td class="action">{{ board.get_area_display }}</td>
                                <td class="text-start">
                                    <a href="{% url 'community:board_detail' board.id %}">
                                        {{ board.title }} 
                                            <span class=" small ml-2"> 
                                                {% if board.reply_set.count > 0 %}
                                                    ( {{ board.reply_set.count }} )
                                               {% endif %}
                                            </span>
                                    </a>  
                                </td>
                                <td class="name">{{ board.writer }}</td>
                                <td class="fs-6">{{ board.created_dt|date:"Y-m-d" }}</td>
                            </tr>

                    {% endfor %}
                    {% else %}
                    
                    <tr>
                        <td colspan="3">등록된 게시글이 없습니다.</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>
        <!--페이징 처리 시작-->
        <div class="row g-0">
            <div class="col-sm-6 col-md-8">
                <ul class="pagination justify-content-center">
                    {% if board_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="javascript:void(0)">이전</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
                    </li>
                    {% endif %}
                    <!--페이지 리스트-->
                    {% for page_number in board_list.paginator.page_range %}
                    {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %}
                    {% if page_number == board_list.number %}
                        <li class="page-item active"><a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">
                            {{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item"><a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">
                            {{ page_number }}</a>
                        </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    <!--다음 페이지-->
                    {% if board_list.has_next %}
                    <li class="page-item"><a class="page-link" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">다음</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
                    </li>
                    {% endif %}
                </ul>
                <!--페이징 처리 끝-->
            </div>
            <div class="col-6 col-md-4">
                <div class="d-grid d-md-flex justify-content-md-end">
                    <button class="btn btn-danger" type="button">
                        <a href="{% url 'community:board_create' %}" class="text-white">글 작성</a>
                    </button>
                </div>
            </div>
        </div>    
    </div>
    <form id="searchForm" method="get" action="{% url 'community:board_list' %}">
        <input type="hidden" id="area" name="area" value="{{ area_text }}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>
</section>
{% endblock %}

<!--자바스크립트 블록-->
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});

const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});


const area_filter = document.getElementById("area_filter");
area_filter.addEventListener('change', function() {
    document.getElementById('kw').value = '';
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('area').value = document.getElementById('area_filter').value;
    document.getElementById('searchForm').submit(); 
});

</script>
{% endblock %}

server_dev/templates/community/board_detail.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<section class="py-10 bg-white">
    <div class="mb-1 p-sm-5">
        <div class="d-block p-5 gold-2 gold-1">
            <hr><h2>제목 : {{ board.title }}</h2>
            <div class="d-grid gap-2">
                <button type="button" class="gold-4" disabled>작성일자: {{ board.created_dt }}</button>
            </div>
            <p class="fs-5 gold-3">{{ board.content }}</p>
            <hr>
                <form action="{% url 'community:reply_create' board.id %}" method="POST">
                    {% csrf_token %}
                    {% block comments %}
                    {% for comment in comment_view %}
                    
                    <p>{{ comment.author }}</p>
                    {% comment %} <p>작성자</p> {% endcomment %}
                    <p>{{ comment.reply }}</p>   
                    <p class="text-end fs-6">{{ comment.created_dt }}</p>
                    <hr>
                    {% endfor %}
                    {% endblock %}
                <!-- 오류표시 Start -->
                {% if form.errors %}
                <div class="gold-11 alert-danger" role="alert">
                    {% for field in form %}
                    {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% endif %} 
                <!-- 오류표시 End -->
                <div class="form-group py-3">
                    <textarea name="reply" id="reply" rows="2" class="form-control"></textarea>
                </div>
                <div class="d-flex bd-highlight mb-3">
                    <div class="p-2 bd-highlight">
                        <button type="button" class="btn btn-danger" onclick="location.href='/comm/board'">돌아가기</button>
                    </div>
                    <div class="ms-auto p-2 bd-highlight">
                        <input type="submit" value="댓글 작성" class="btn btn-danger">
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

server_dev/templates/community/board_write.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<section class="py-10 bg-white" style="height: calc(96vh - 19px); width: 100%;">
    <div class="mb-1 p-sm-5">
        <div class="row gold-1 gold-9">
            <form  method="POST">
                {% csrf_token %}
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                    {% if field.errors %}
                    <div>
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                <div class="mb-3">
                    <label for="title" class="form-label">제목</label>
                    <input type="text" class="form-control" name="title" id="title"
                           value="{{ form.title.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="content" class="form-label">내용</label>
                    <textarea class="form-control" name="content"
                              id="content" rows="5">{{ form.content.value|default_if_none:'' }}</textarea>
                </div>
                <div class="mb-3">
                    <label for="area" class="form-label">지역</label>
                    <select class="form-select sm" name="area" id="area" >
                        {% for i, j in form.fields.area.choices %}
                        <option value="{{ i }}" {% if form.fields.area.value == i %} {% endif %}>{{ j }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="gold-11 alert-danger d-flex align-items-center" role="alert">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dot" viewBox="0 0 16 16">
                        <path d="M8 9.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
                    </svg>
                    <div>
                      지역을 선택하세요
                    </div>
                </div>
                <div class="d-flex bd-highlight mb-3">
                    <div class="p-2 bd-highlight">
                        <button type="button" class="btn btn-danger" onclick="location.href='/comm/board'">돌아가기</button> 
                    </div>
                    <div class="ms-auto p-2 bd-highlight">
                        <button type="submit" class="btn btn-danger">글 작성</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}

server_dev/templates/community/comm.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Mashead header-->
<header class="p-5">
    <div class="container px-5 px-lg-5 my-5 mt-10">
        <h5>커뮤니티</h5>
        <div class="row">
            <div class="col-sm-6">
                <label style="margin-right: 8px;" class="">
                    <div class="icheckbox_square-blue" style="position: relative;"><input type="checkbox" id="check-all" class="icheck" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"><ins class="iCheck-helper" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);"></ins></div>
                </label>
                <div class="btn-group">
                    <button type="button" class="btn btn-danger" data-toggle="dropdown">
                        지역선택 <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">강남구</a></li>
                    </ul>
                </div>
                <p style="float:right; flex-direction:column;">마트 할인</p><input type="checkbox" style="float:right;">
            </div>
            <div class="col-md-6 search-form">
                <form action="#" class="text-right">
                    <div class="input-group">
                        <input type="text" class="form-control input-sm" placeholder="Search">
                        <span class="input-group-btn">
                            <button type="submit" name="search" class="btn btn-danger btn-sm search"><i class="fa fa-search"></i></button></span>
                    </div>			 
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table">
                <tbody>
                    <tr>
                        <!--td class="action"><input type="checkbox" /></!--td-->
                        <th>번호</th>
                        <!--td class="action"><i class="fa fa-star-o"></i></!--td-->
                        <th>지역</th>
                        <th class="action"><i class="fa fa-bookmark-o"></i></th>
                        <th class="name">작성자</th>
                        <th class="subject">제목</th>
                        <th class="time">작성일시</th>
                    </tr>
                    <tr>
                        <td class="action">1</td>
                        <td class="action">강남구</i></td>
                        <td class="action"><i class="fa fa-bookmark-o"></i></td>
                        <td class="name"><a href="#">Larry Gardner</a></td>
                        <td class="subject"><a href="#">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed </a></td>
                        <td class="time">08:30 PM</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <ul class="pagination">
            <li class="disabled"><a href="#">«</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">»</a></li>
        </ul>						
    </div>
</header>
{% endblock %}