server_dev/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('main/', include('main.urls')),
    path('comm/', include('community.urls')),
    path('user/', include('user.urls')),
    path('mart/', include('mart.urls')),
]

server_dev/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name="index"),
    path('second/',views.second, name="second"),
    path('third/',views.third, name="third")
]

server_dev/server_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('main/', include('main.urls')),
    path('comm/', include('community.urls')),
    path('user/', include('user.urls')),
    path('mart/', include('mart.urls')),
]

server_dev/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import inquirys

app_name = 'user'

urlpatterns = [
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/',views.signup, name='signup'),
    path('corpsignup/',views.corpsignup, name='corpsignup'),
    path('signselect/',views.signselect, name='signselect'),

    path('', inquirys, name='inquirys'), #문의하기 데이터를 처리할 URL


    path('idCheck/',views.idCheck, name="idCheck"),
    path('ent_search/',views.ent_search, name="ent_search"),

    # mypage
    path('mypage/',views.mypage, name='mypage'),
    path('edit/',views.member_edit, name='member_edit'),
    path('upload/',views.sale_upload, name='sale_upload'),
    path('sale_edit/<int:sale_id>/',views.sale_edit, name='sale_edit'),

]

server_dev/user/models.py
from django.db import models
from django.utils import timezone
#from django.contrib.auth.models import AbstractUser

# from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

# USER_ROLES = {
#     'ROLE_NOMAL' : 'NORMAL',
#     'ROLE_COMPANY' : 'COMPANY',
#     'ROLE_SUPER' : 'SUPER'
# }

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=100)
    user_id = models.CharField(max_length=50, unique=True)
    user_phone = models.CharField(max_length=40, verbose_name='유저 전화번호')
    user_addr = models.CharField(max_length=40, verbose_name='유저 주소')
    user_level =models.CharField(max_length=8 ,verbose_name="등급")

    def __str__(self): #2
        return self.user_id
    
    class Meta: #3
        db_table = 'TB_USER'
        verbose_name = '유저'
        verbose_name_plural = '유저'
    
    


# 문의하기 Table
class secinquiry(models.Model):
    inquirys_name = models.CharField(max_length=20)
    inquirys_email = models.CharField(max_length=30)
    inquirys_text = models.TextField(max_length=500)

    class Meta: #3
        db_table = 'TB_inquiry'


# sale이력 Table
class ThSale(models.Model):
    sale_name = models.CharField(max_length=30)
    user = models.CharField(max_length=20)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.sale_name

    class Meta: #3
        db_table = 'TH_SALE'

class ThSaleDetail(models.Model):
    sale = models.ForeignKey('ThSale', on_delete=models.CASCADE)
    gd_type_cd = models.CharField(max_length=10)
    sale_gds = models.CharField(max_length=100)
    sale_price = models.IntegerField()

    class Meta:
        db_table = 'TH_SALED'
        

server_dev/user/forms.py
from django import forms
from .models import User, ThSale
from argon2 import PasswordHasher, exceptions
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class LoginForm(forms.Form):
    user_id = forms.CharField(
        max_length=32,
        label='아이디',
        widget=forms.TextInput(
        ),
        error_messages={'required' : '아이디를 입력하세요.'}
    )

    password = forms.CharField(
        max_length=128,
        label='비밀번호',
        widget=forms.PasswordInput,
        error_messages={'required' : '비밀번호를 입력하세요.'}
    )

    field_order = [
        'user_id',
        'password'
    ]

    def clean(self):
        cleaned_data = super().clean()
 
        user_id = cleaned_data.get('user_id', '')
        password = cleaned_data.get('password', '')
        if user_id and password :
            try:
                user = User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                print("아이디 없음")
                return self.add_error('user_id', '아이디가 존재하지 않습니다.')

            try:
                PasswordHasher().verify(user.password, password)
            except exceptions.VerifyMismatchError:
                print("비번 없음")
                return self.add_error('password', '비밀번호가 다릅니다.')
            
            self.login_session = user.user_id


class SaleForm(forms.ModelForm):
    class Meta:
        model = ThSale
        fields = ['sale_name','start_date', 'end_date']

server_dev/user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import LoginForm
from argon2 import PasswordHasher
#from user.forms import UserForm

from .models import *
from django.db import connection
from main.func import dictfetchall
from datetime import datetime, timedelta
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

import json
# Create your views here.

#개인&회사 회원가입
def signup(request):
    if request.method == 'GET':
        return render(request, 'user/signup.html')   
    elif request.method =='POST':
        user_name = request.POST.get('user_id','')
        user_id = request.POST.get('username','')
        firstpassword = request.POST.get('password','')
        secpassword = request.POST.get('password2','')
        user_phone = request.POST.get('user_phone','')
        user_addr = request.POST.get('user_addr','')
        user_level = request.POST.get('user_level','')

        if (user_name or user_id or user_phone or firstpassword or secpassword or user_addr) == '':
            return redirect('/user/signup')
        elif firstpassword != secpassword:
            return redirect('/user/signup')
        else:
            usersave = User(username=user_id, password=PasswordHasher().hash(firstpassword), user_id=user_name , user_phone=user_phone, user_addr=user_addr,user_level=user_level)
            usersave.save()
        return redirect('main:index')

# #회사 회원가입
def corpsignup(request):
    if request.method == 'GET':
        cursor = connection.cursor()
        sql = "select distinct ent_nm from tb_ent;"
        cursor.execute(sql)
        ent_nm = dictfetchall(cursor)
        connection.close()
        return render(request, 'user/corpsignup.html',{"ent_nms":ent_nm})
    elif request.method =='POST':
        user_name = request.POST.get('user_id','')
        user_id = request.POST.get('username','')
        firstpassword = request.POST.get('password','')
        secpassword = request.POST.get('password2','')
        user_phone = request.POST.get('user_phone','')
        user_addr = request.POST.get('user_addr','')
        user_level = request.POST.get('user_level','')

        if (user_name or user_id or user_phone or firstpassword or secpassword or user_addr) == '':
            return redirect('/user/signup')
        elif firstpassword != secpassword:
            return redirect('/user/signup')
        else:
            usersave = User(username=user_id, password=PasswordHasher().hash(firstpassword), user_id=user_name , user_phone=user_phone, user_addr=user_addr, user_level=user_level)
            usersave.save()
        return redirect('main:index')

#회원가입 누르면 개인, 회사 나눠놓은것
def signselect(request):
    return render(request, 'user/signselect.html')

#로그인
def login(request):
    loginform = LoginForm()
    context = {'forms' : loginform }
    if request.method == 'GET':
        return render(request, 'user/login.html', context)
    elif request.method == 'POST':
        loginform = LoginForm(request.POST)
        if loginform.is_valid():
            request.session['login_session'] = loginform.login_session
            request.session.set_expiry(0)
            
            return redirect('main:index')
        else:
            context['forms'] = loginform
            if loginform.errors:
                for value in loginform.errors.values():
                    context['error'] = value
        
        return render(request, 'user/login.html', context)

# 로그아웃
def logout(request):
    request.session.flush()
    # if request.session.get('login_session'):
    #     del request.session['login_session']
    return redirect('/')


#문의하기
def inquirys(request):
    if request.method == 'POST':
        #print(request.POST)
        inquirys_name = request.POST.get('quname')
        inquirys_email = request.POST.get('quemail')
        inquirys_text = request.POST.get('qutext')
        new_inquirys = secinquiry(inquirys_name=inquirys_name, inquirys_email=inquirys_email, inquirys_text=inquirys_text)
        new_inquirys.save()
    return redirect('/')


# mypage
def mypage(request):
    login_session = request.session.get('login_session', '')
    userdata = User.objects.get(user_id = login_session)
    if userdata.user_level == '1':
        return render(request, 'user/history_search.html', {"login_session":login_session})
    else:
        cursor = connection.cursor()
        sql = "select id, sale_name, (select concat(group_concat(d.gd_type_2 SEPARATOR ', '),' 등') " + \
              "from (select distinct gd_type_cd from th_saled b where a.id = b.sale_id LIMIT 3) c, tb_gd_cd d where c.gd_type_cd = d.gd_type_cd) as 'sale_gds'," + \
              "(select count(*) from th_saled b where a.id = b.sale_id) as 'sale_gds_cnt'," + \
              "concat(date_format(start_date,'%Y/%m/%d'), ' ~ ', date_format(end_date,'%Y/%m/%d')) as 'sale_date'" + \
              "from th_sale a where user='" + login_session + "' order by start_date desc, end_date desc;"
        cursor.execute(sql)
        result = dictfetchall(cursor)
        cursor.close()
        return render(request, 'user/history_sale.html', {"sale_data":result, "login_session":login_session})

def member_edit(request):
    login_session = request.session.get('login_session', '')
    userdata = User.objects.get(user_id = login_session)
    if request.method == 'POST':
        phone = request.POST.get('phone')
        addr = request.POST.get('addr')
        if phone:
            userdata.user_phone = phone 
        if addr:
            userdata.user_addr = addr
        userdata.save()
        return render(request, 'user/member_save.html', {"login_session":login_session})
    
    return render(request, 'user/member_edit.html', {"userdata":userdata, "login_session":login_session})

def sale_upload(request):
    login_session = request.session.get('login_session', '')
    cursor = connection.cursor()
    if request.method == 'POST':
        sale_name = request.POST.get('sale_name')
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        end_date = datetime.strptime(end_date, '%Y-%m-%d') + timedelta(hours=23, minutes=59, seconds=59)
        sale = ThSale(sale_name=sale_name, user=login_session, start_date=start_date, end_date=end_date)
        sale.save()
        count = request.POST.get('table_count')
        
        for i in range(1,int(count)+1):
            try:
                num = str(i)
                # gd_type_nm = request.POST.get('gd_type'+num)
                sale_gds = request.POST.get('sale_gds'+num)
                sale_price = request.POST.get('sale_price'+num)
                gd_type_sql = "select gd_type_cd from tb_gds where gd_nm = '" + sale_gds + "';"
                cursor.execute(gd_type_sql)
                gd_type_cd = cursor.fetchall()[0][0]
                sale_detail = ThSaleDetail(sale=sale, gd_type_cd=gd_type_cd, sale_gds=sale_gds , sale_price=sale_price)
                sale_detail.save()
            except:
                pass
        return redirect('user:mypage')
    sql = "select distinct(gd_nm) from tb_gds;"
    cursor.execute(sql)
    gd_nms = dictfetchall(cursor)
    connection.close()
    return render(request, 'user/sale_upload.html', {"gd_nms":gd_nms, "login_session":login_session})

def sale_edit(request, sale_id):
    login_session = request.session.get('login_session', '')
    sale = get_object_or_404(ThSale, pk=sale_id)
    saleSql = "select gd_type_2, sale_gds, sale_price from th_saled a, tb_gd_cd b where a.gd_type_cd = b.gd_type_cd and sale_id = " + str(sale_id) +";"
    cursor = connection.cursor()
    cursor.execute(saleSql)
    saled = dictfetchall(cursor)
    connection.close()
    return render(request, 'user/sale_edit.html', {"sale":sale,"saled":saled,"login_session":login_session})

@csrf_exempt
def ent_search(request):
    jsonObject = json.loads(request.body)
    ent_nm =   jsonObject.get('ent_nm')
    entsql = "select * from tb_ent where ent_nm ='" + ent_nm + "';"
    usersql = "select * from tb_user where username='" + ent_nm + "';"
    cursor = connection.cursor()
    cursor.execute(entsql)
    ent_info = dictfetchall(cursor)
    cursor.execute(usersql)
    user_info = dictfetchall(cursor)
    connection.close()
    if ent_info:
        if user_info:
            return JsonResponse({"alert":"이 업체는 이미 존재합니다."})
        return JsonResponse(ent_info[0])
    return JsonResponse({"alert":"찾으시는 업체가 없습니다."})
    

@csrf_exempt
def idCheck(request):
    jsonObject = json.loads(request.body)
    user_id = jsonObject.get('user_id')
    usersql = "select * from tb_user where user_id ='" + user_id + "';"
    cursor = connection.cursor()
    cursor.execute(usersql)
    user_info = dictfetchall(cursor)
    connection.close()
    if user_info:
        return JsonResponse({"alert":"아이디가 이미 존재합니다."})
    return JsonResponse({})

server_dev/templates/user/corpsignup.html
{% extends 'base.html' %}
{% comment %} 회사 회원가입 {% endcomment %}
{% load static %}
{% block content %}
<section class="py-10 bg-white" style="height: calc(96vh - 19px); width: 100%;">
    <div class="container my-3 mt-5" style="width:65vmin">
        <form method="post" name="frm" action="{% url 'user:signup' %}">
            {% csrf_token %}
            <div class="mb-4">
                <label for="user_id" class="col-md-4 text-right">사용자 ID<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="text" class="form-control" name="user_id" id="user_id" value="{{ form.user_id.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="username" class="col-md-4 text-right">회사명<span style="color:red;"> * </span>:</label>
                <button type="button" class="col-md-1 btn btn-danger search gold-106"><i class="fa fa-search"></i></button>
                <div class="col-md-6 gold-106" width="100%">
                    <input type="text" class="form-control" name="username" id="username" list="ent_list" value="{{ form.username.value|default_if_none:'' }}">
                    <datalist id="ent_list" name="ent_list">
                        {% for ent in ent_nms %}
                            <option value="{{ent.ent_nm}}" />
                        {% endfor %}
                    </datalist>
                    
                </div>
            </div>
            <div class="mb-4">
                <label for="password" class="col-md-4 text-right">비밀번호<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="password2" class="col-md-4 text-right">비밀번호 확인<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="user_phone" class="col-md-4 text-right">회사 전화번호<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="text" class="form-control" name="user_phone" id="user_phone" value="{{ form.user_phone.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="user_addr" class="col-md-4 text-right">회사 주소<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="text" class="form-control" name="user_addr" id="user_addr" value="{{ form.user_addr.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                
                <div class="col-md-7 gold-106">
                    <input type="hidden" class="form-control" name="user_level" id="user_level" value="2">
                </div>
            </div>
            <div style="text-align: center;">
                <button type="button" class="btn btn-danger" onclick="checkForm();">생성하기</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}
{% block script %}
<script>
    let btnSh = document.querySelector('.search')
    btnSh.addEventListener('click',e => {
        let ent_nm = document.querySelector("#username").value;
        $.ajax({
            url : '{% url 'user:ent_search' %}',
            type : 'POST',
            data : JSON.stringify({"ent_nm":ent_nm}),
            success:function(data){
                if(data.ENT_NM){
                    document.querySelector("#user_phone").value = data.ENT_PHONE;
                    document.querySelector("#user_addr").value = data.ENT_ADDR;
                }
                else {
                    document.querySelector("#username").value = "";
                    document.querySelector("#user_phone").value = "";
                    document.querySelector("#user_addr").value = "";
                    alert(data.alert);
                }
            },
            error: function(){
                alert('ERROR');
            }
        });
    });
    function checkForm(){
        if(frm.user_id.value == "") {
            frm.user_id.focus();
            alert("ID를 입력해 주십시오.");
        }
        else if(frm.username.value == "") {
            frm.username.focus();
            alert("회사명을 입력해 주십시오.");
        }
        else if(frm.password.value == "") {
            frm.password.focus();
            alert("비밀번호를 입력해 주십시오.");
        }
        else if(frm.password.value != frm.password2.value) {
            frm.password2.focus();
            alert("비밀번호가 일치하지않습니다.");
        }
        else {
            frm.submit();
        }
    }
</script>
{% endblock %}

server_dev/templates/user/history_sale.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,300,0,0"
/>
<section class="gold-102 px-5 bg-white">
  <div class="container gold-101 my-3 mt-5" style="display: flex; flex-wrap: wrap">
    <div class="col-lg-2">
      <table class="col-md-12">
        <tbody>
          <tr>
            <td class="col-md-3" style="text-align: center; min-width: 40px">
              <span class="material-symbols-outlined">history</span>
            </td>
            <td class="col-md-9" style="font-size: 11pt; min-width: 130px">
              세일 이력
            </td>
          </tr>
          <tr
            onclick="location.href='{% url 'user:member_edit' %}'"
            style="cursor: hand"
          >
            <td class="col-md-3" style="text-align: center">
              <span class="material-symbols-outlined">settings</span>
            </td>
            <td class="col-md-9" style="font-size: 11pt">회원 정보 수정</td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- End Menu -->
    <div class="col-lg-10">
      <div class="card-style">
        <div
          class="title d-flex flex-wrap align-items-center justify-content-between"
        >
          <div>
            <div style="float: left" class="py-2 gold-104">
              <h4>세일 이력</h4>
            </div>
            <div style="float: left; font-size: 0.8rem" class="ms-sm-4">
              <button
                type="button"
                class="btn btn-danger"
                style="font-size: 0.8rem"
                onclick="location.href='{% url 'user:sale_upload' %}'"
              >
                등록하기
              </button>
            </div>
          </div>
        </div>
        <!-- End Title -->
        <div class="table-responsive" style="height:calc(55vh - 20px);overflow:auto;">
          <table class="table">
            <thead>
              <tr>
                <th>세일명</th>
                <th class="d-sm-table-cell">세일 품목</th>
                <th class="d-sm-table-cell">세일 품목 수</th>
                <th>세일 기간</th>
              </tr>
            </thead>
            <tbody id="my-tbody">
              {% if sale_data %}
              {% for data in sale_data %}
                <tr onclick="location.href='{% url 'user:sale_edit' data.id %}'" style="cursor: hand">
                  <td>
                    <p class="gold-105">{{ data.sale_name }}</p>
                  </td>
                  <td>
                    <p class="gold-105">{{ data.sale_gds }}</p>
                  </td> 
                  <td>
                    <p class="gold-105">{{ data.sale_gds_cnt }}</p>
                  </td>
                  <td>
                    <p class="gold-105">{{ data.sale_date }}</p>
                  </td>
                </tr>
              {% endfor %}
              {% else %}
              <tr>
                <td colspan="4"><p class="gold-105">세일 이력이 없습니다.</p></td>
              </tr>
              {% endif %}
            </tbody>
          </table>
          <!-- End Table -->
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{% block script %}
<script>
  function delete_row(obj) {
    var my_tbody = document.getElementById('my-tbody');
    if(my_tbody.rows.length<2) return;
    var tr = $(obj).parent().parent();
    tr.remove();
  }
</script>
{% endblock%}

server_dev/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="py-10 bg-white" style="height: calc(96vh - 19px); width: 100%;">
  <div class="container px-5 mt-5"  style="width:65vmin">
    <form method="post" class="post-form" action="{% url 'user:login' %}">
    {% csrf_token %}
    {% for field in forms %}
      <div class="mb-3">
        <label for="{{field.name}}">{{field.label}}</label>
        <input type="{{field.field.widget.input_type}}" class="form-control" name="{{field.name}}" id="{{field.name}}" value="{{ field.user_id.value|default_if_none:'' }}">
        {% if field.errors %}
          <div>{{ field.errors }}</div>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-danger">로그인</button>
    <button type="button" class="btn btn-danger" onclick="location.href='{% url 'user:signselect' %}'">회원가입</button>
    </form>
  </div>
</section>
{% endblock %}

server_dev/templates/user/member_save.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link
  rel="stylesheet"
  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,300,0,0"
/>
<section class="gold-102 px-5 bg-white">
  <div class="container gold-101 my-3 mt-5" style="display: flex; flex-wrap: wrap;">
    <div class="col-lg-2">
      <table class="col-md-12">
        <tbody>
          <tr
            onclick="location.href='{% url 'user:mypage' %}'"
            style="cursor: hand"
          >
            <td class="col-md-3" style="text-align: center; min-width: 40px">
              <span class="material-symbols-outlined">history</span>
            </td>
            <td class="col-md-9" style="font-size: 11pt; min-width: 130px">
              검색 이력
            </td>
          </tr>
          <tr>
            <td class="col-md-3" style="text-align: center">
              <span class="material-symbols-outlined">settings</span>
            </td>
            <td class="col-md-9" style="font-size: 11pt">회원 정보 수정</td>
          </tr>
        </tbody>
      </table>
    </div>
    <!-- End Col -->
    <div class="col-lg-10">
      <div class="card-style">
        <div>
          <div class="py-2">
            <h4>회원 정보 수정</h4>
          </div>
          <!-- End Title -->
          <div class="container my-3" style="width: 65vmin">
            <h3>수정 완료!</h3>
          </div>
        </div>
      </div>
    </div>
    <!-- End Col -->
  </div>
</section>
{% endblock %}

server_dev/templates/user/signselect.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="py-10 bg-white" style="height: calc(96vh - 19px); width: 100%; ">
    <form method="post" class="post-form" action="signup.html">
    <div class="container px-5 mt-5"  style="width:100vmin;">
        <div style="margin-top: 90px; margin-bottom:30px; text-align: center;  ">
            <h3> 회원 가입 </h3>
        </div>
        <div style="margin-bottom:30px;">
            <a href="{% url 'user:signup' %}" class="gold-107 gold-110 gold-109">
                일반 사용자
            </a>
        </div>
    
        <div class="gold-107 gold-112 gold-111" >
            <a href="{% url 'user:corpsignup' %}" class="gold-107 gold-111 gold-112">    
                회사&사업자
            </a>
        </div>

        
        
        <div class="clear"></div>
</section>
{% endblock %}

server_dev/templates/user/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="py-10 bg-white" style="height: calc(96vh - 19px); width: 100%;">
    <div class="container my-3 mt-5" style="width:65vmin">
        <form method="post" name="frm" action="{% url 'user:signup' %}">
            {% csrf_token %}
            <div class="mb-4">
                <label for="user_id" class="col-md-4 text-right">사용자 ID<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="text" class="form-control" name="user_id" id="user_id" value="{{ form.user_id.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="username" class="col-md-4 text-right">사용자 이름<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="password" class="col-md-4 text-right">비밀번호<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="password2" class="col-md-4 text-right">비밀번호 확인<span style="color:red;"> * </span>:</label>
                <div class="col-md-7 gold-106">
                    <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="user_phone" class="col-md-4 text-right">전화번호&emsp;:</label>
                <div class="col-md-7 gold-106">
                    <input type="text" class="form-control" name="user_phone" id="user_phone" value="{{ form.user_phone.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="user_addr" class="col-md-4 text-right">주소&emsp;:</label>
                <div class="col-md-7 gold-106">
                    <input type="text" class="form-control" name="user_addr" id="user_addr" value="{{ form.user_addr.value|default_if_none:'' }}">
                </div>
            </div>
            <div class="mb-4">
                <div class="col-md-7 gold-106">
                    <input type="hidden" class="form-control" name="user_level" id="user_level" value="1">
                </div>
            </div>
            <div style="text-align: center;">
                <button type="button" class="btn btn-danger" onclick="checkForm();">생성하기</button>
            </div>
        </form>
    </div>
</section>
{% endblock %}
{% block script %}
<script>
    function checkForm(){
        if(frm.user_id.value == "") {
            frm.user_id.focus();
            alert("ID를 입력해 주십시오.");
        }
        else if(frm.username.value == "") {
            frm.username.focus();
            alert("이름을 입력해 주십시오.");
        }
        else if(frm.password.value == "") {
            frm.password.focus();
            alert("비밀번호를 입력해 주십시오.");
        }
        else if(frm.password.value != frm.password2.value) {
            frm.password2.focus();
            alert("비밀번호가 일치하지않습니다.");
        }
        else {
            let user_id = document.querySelector("#user_id").value;
            $.ajax({
                url : '{% url 'user:idCheck' %}',
                type : 'POST',
                data : JSON.stringify({"user_id":user_id}),
                success:function(data){
                    if(data.alert){
                        alert(data.alert);
                    }
                    else {
                        frm.submit();
                    }
                },
                error: function(){
                    alert('ERROR');
                }
            });
        }
    }
</script>
{% endblock %}