server_dev/community/urls.py
from django.urls import path
from . import views


app_name = 'community'

urlpatterns = [
    path('board/',views.board_list, name='board_list'),
    path('<int:board_id>/', views.board_detail, name='board_detail'),
    path('reply/create/<int:board_id>/', views.reply_create, name='reply_create'),
    path('board/create/', views.board_create, name='board_create'),
]

server_dev/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('main/', include('main.urls')),
    path('comm/', include('community.urls')),
    path('user/', include('user.urls')),
    path('mart/', include('mart.urls')),
]

server_dev/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name="index"),
    path('second/',views.second, name="second"),
    path('third/',views.third, name="third")
]

server_dev/mart/urls.py
from django.urls import path
from . import views

app_name = 'mart'

urlpatterns = [
    path('',views.martSearch, name="martSearch"),
]

server_dev/server_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('main/', include('main.urls')),
    path('comm/', include('community.urls')),
    path('user/', include('user.urls')),
    path('mart/', include('mart.urls')),
]

server_dev/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import inquirys

app_name = 'user'

urlpatterns = [
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('signup/',views.signup, name='signup'),
    path('corpsignup/',views.corpsignup, name='corpsignup'),
    path('signselect/',views.signselect, name='signselect'),

    path('', inquirys, name='inquirys'), #문의하기 데이터를 처리할 URL


    path('idCheck/',views.idCheck, name="idCheck"),
    path('ent_search/',views.ent_search, name="ent_search"),

    # mypage
    path('mypage/',views.mypage, name='mypage'),
    path('edit/',views.member_edit, name='member_edit'),
    path('upload/',views.sale_upload, name='sale_upload'),
    path('sale_edit/<int:sale_id>/',views.sale_edit, name='sale_edit'),

]

server_dev/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>금나싸다</title>
        <link rel="icon" href="{% static 'assets/img/mark.png' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}?after" />
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />

        
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav"> 
            <div class="container px-5">
                <a href="{% url 'main:index' %}"><img src="{% static '/assets/img/mark.png' %}" style="width:80px; height:80px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="bi-list"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'community:board_list' %}">커뮤니티</a></li>
                        <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'mart:martSearch' %}">마트검색</a></li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        
                        {% if login_session %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:mypage' %}">{{ login_session }}님</a></li>
                            <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'user:logout' %}">(로그아웃)</a></li>    
                        {% else %}
                            <li class="nav-item"><a class="nav-link me-lg-3" href="{% url 'user:login' %}">로그인</a></li>
                        {% endif %}
                            
                    </ul>
                    <button class="btn btn-outline-danger rounded-pill px-3 mb-2 mb-lg-0" data-bs-toggle="modal" data-bs-target="#feedbackModal">
                        <span class="d-flex align-items-center">
                            <i class="bi-chat-text-fill me-2"></i>
                            <span class="small">문의하기</span>
                        </span>
                    </button>
                </div>
            </div>
        </nav>
        <!-- Mashead header-->
        <!-- 기본 템플릿 안에 삽입할 내용 Start-->
        {% block content %}
        {% endblock %}
        <!--기본 템플릿 안에 삽입될 내용 End -->
        <!-- Footer-->
        <footer class="bg-black text-center py-1">
            <div class="container px-5">
                <div class="text-white-50 small">
                    <div class="mb-2">&copy; Your Website 2022. All Rights Reserved.</div>
                    <a href="#!">Privacy</a>
                    <span class="mx-1">&middot;</span>
                    <a href="#!">Terms</a>
                    <span class="mx-1">&middot;</span>
                    <a href="#!">FAQ</a>
                </div>
            </div>
        </footer>
        <!-- Feedback Modal-->
        <div class="modal fade" id="feedbackModal" tabindex="-1" aria-labelledby="feedbackModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header bg-danger p-4">
                        <h5 class="modal-title font-alt text-white" id="feedbackModalLabel">문의하기</h5>
                        <button class="btn-close btn-close-white" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body border-0 p-4">
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- * * SB Forms Contact Form * *-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- This form is pre-integrated with SB Forms.-->
                        <!-- To make this form functional, sign up at-->
                        <!-- https://startbootstrap.com/solution/contact-forms-->
                        <!-- to get an API token!-->
                        <form action="{% url 'user:inquirys' %}" method="post" id="contactForm">{% csrf_token %}
                            <!-- Name input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="name" type="text" placeholder="이름을 적어주세요." data-sb-validations="required" name="quname" />
                                <label for="name">이름</label>
                                <div class="invalid-feedback" data-sb-feedback="name:required">이름은 필수입니다.</div>
                            </div>
                            <!-- Email address input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" name="quemail"/>
                                <label for="email">이메일 주소</label>
                                <div class="invalid-feedback" data-sb-feedback="email:required">이메일은 필수입니다.</div>
                            </div>
                            <!-- Message input-->
                            <div class="form-floating mb-3">
                                <textarea class="form-control" id="message" type="text" placeholder="문의 할 내용을 입력하세요." style="height: 10rem" data-sb-validations="required" name="qutext"></textarea>
                                <label for="message">문의내용</label>
                                <div class="invalid-feedback" data-sb-feedback="message:required">문의 내용을 적어주세요</div>
                            </div>
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">문의내용 전송완료</div>
                                    <br />
                                    {% comment %} <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a> {% endcomment %}
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">문의 오류</div></div>
                            <!-- Submit Button-->
                            <div class="d-grid"><button class="btn-danger rounded-pill btn-lg" id="submitButton" type="submit">문의하기</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <!--<script src="{% static 'js/scripts.js' %}"></script>-->
        <!-- 자바스크립트 Start -->
        {% block script %}
        {% endblock %}
        <!-- 자바스크립트 End -->
    </body>
</html>