server_dev/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('main/', include('main.urls')),
    path('comm/', include('community.urls')),
    path('user/', include('user.urls')),
    path('mart/', include('mart.urls')),
]

server_dev/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name="index"),
    path('second/',views.second, name="second"),
    path('third/',views.third, name="third")
]

server_dev/server_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('main/', include('main.urls')),
    path('comm/', include('community.urls')),
    path('user/', include('user.urls')),
    path('mart/', include('mart.urls')),
]

server_dev/main/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from user.models import User


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class CommunityMainboard(models.Model):
    area = models.CharField(max_length=8)
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_dt = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'community_mainboard'


class CommunityReply(models.Model):
    reply = models.TextField()
    created_dt = models.DateTimeField()
    post = models.ForeignKey(CommunityMainboard, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'community_reply'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class TbEnt(models.Model):
    ent_num = models.IntegerField(db_column='ENT_NUM', primary_key=True)  # Field name made lowercase.
    ent_area_cd = models.ForeignKey('TbEntArea', models.DO_NOTHING, db_column='ENT_AREA_CD')  # Field name made lowercase.
    ent_type_cd = models.ForeignKey('TbEntType', models.DO_NOTHING, db_column='ENT_TYPE_CD')  # Field name made lowercase.
    ent_nm = models.CharField(db_column='ENT_NM', max_length=50)  # Field name made lowercase.
    ent_phone = models.CharField(db_column='ENT_PHONE', max_length=15, blank=True, null=True)  # Field name made lowercase.
    ent_post_no = models.CharField(db_column='ENT_POST_NO', max_length=10, blank=True, null=True)  # Field name made lowercase.
    ent_addr = models.CharField(db_column='ENT_ADDR', max_length=100, blank=True, null=True)  # Field name made lowercase.
    map_x = models.FloatField(db_column='MAP_X')  # Field name made lowercase.
    map_y = models.FloatField(db_column='MAP_Y')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tb_ent'


class TbEntArea(models.Model):
    ent_area_cd = models.IntegerField(db_column='ENT_AREA_CD', primary_key=True)  # Field name made lowercase.
    ent_area_nm = models.CharField(db_column='ENT_AREA_NM', max_length=30)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tb_ent_area'


class TbEntType(models.Model):
    ent_type_cd = models.CharField(db_column='ENT_TYPE_CD', primary_key=True, max_length=2)  # Field name made lowercase.
    ent_type_nm = models.CharField(db_column='ENT_TYPE_NM', max_length=12)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tb_ent_type'


class TbGdCd(models.Model):
    gd_type_cd = models.CharField(db_column='GD_TYPE_CD', primary_key=True, max_length=10)  # Field name made lowercase.
    gd_type_1 = models.CharField(db_column='GD_TYPE_1', max_length=30)  # Field name made lowercase.
    gd_type_2 = models.CharField(db_column='GD_TYPE_2', max_length=30)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tb_gd_cd'


class TbGds(models.Model):
    gd_num = models.IntegerField(db_column='GD_NUM', primary_key=True)  # Field name made lowercase.
    gd_type_cd = models.ForeignKey(TbGdCd, models.DO_NOTHING, db_column='GD_TYPE_CD')  # Field name made lowercase.
    gd_nm = models.CharField(db_column='GD_NM', max_length=100)  # Field name made lowercase.
    gd_descd = models.CharField(db_column='GD_DESCD', max_length=100, blank=True, null=True)  # Field name made lowercase.
    gd_unit = models.IntegerField(db_column='GD_UNIT', blank=True, null=True)  # Field name made lowercase.
    gd_unit_cd = models.ForeignKey('TbUnit', models.DO_NOTHING, db_column='GD_UNIT_CD')  # Field name made lowercase.
    gd_ent_nm = models.CharField(db_column='GD_ENT_NM', max_length=30)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tb_gds'


class TbIrdent(models.Model):
    recipe_num = models.ForeignKey('TbRecipe', models.DO_NOTHING, db_column='RECIPE_NUM', blank=True, null=True)  # Field name made lowercase.
    irdnt_nm = models.CharField(db_column='IRDNT_NM', max_length=50)  # Field name made lowercase.
    irdnt_type = models.CharField(db_column='IRDNT_TYPE', max_length=20, blank=True, null=True)  # Field name made lowercase.
    gd_type_cd = models.ForeignKey(TbGdCd, models.DO_NOTHING, db_column='GD_TYPE_CD')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tb_irdent'


class TbRecipe(models.Model):
    recipe_num = models.IntegerField(db_column='RECIPE_NUM', primary_key=True)  # Field name made lowercase.
    recipe_nm = models.CharField(db_column='RECIPE_NM', max_length=40)  # Field name made lowercase.
    nation_cd = models.IntegerField(db_column='NATION_CD', blank=True, null=True)  # Field name made lowercase.
    nation_nm = models.CharField(db_column='NATION_NM', max_length=20, blank=True, null=True)  # Field name made lowercase.
    type_cd = models.IntegerField(db_column='TYPE_CD', blank=True, null=True)  # Field name made lowercase.
    type_nm = models.CharField(db_column='TYPE_NM', max_length=25, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tb_recipe'


class TbUnit(models.Model):
    gd_unit_cd = models.CharField(db_column='GD_UNIT_CD', primary_key=True, max_length=4)  # Field name made lowercase.
    gd_unit_nm = models.CharField(db_column='GD_UNIT_NM', max_length=10)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'tb_unit'


class TbUser(models.Model):
    username = models.CharField(unique=True, max_length=50)
    password = models.CharField(unique=True, max_length=100)
    user_id = models.CharField(max_length=50)
    user_phone = models.CharField(max_length=40)
    user_addr = models.CharField(max_length=40)
    user_level = models.CharField(max_length=8)

    class Meta:
        managed = False
        db_table = 'tb_user'


class ThSearch1(models.Model):
    user_id = models.CharField(max_length=30)
    recipe_nm = models.CharField(db_column='RECIPE_NM', max_length=50)  # Field name made lowercase.
    ht_date = models.DateTimeField(db_column='HT_DATE', auto_now_add=True, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        db_table = 'th_search1'


class ThSearch2(models.Model):
    search = models.ForeignKey('ThSearch1', on_delete=models.CASCADE)

server_dev/main/views.py
from django.shortcuts import render
from django.db import connection
import pandas as pd
import json
from django.views.decorators.csrf import csrf_exempt
from .func import crawl
from .models import *
from django.utils.dateformat import DateFormat
from datetime import datetime
from .func import crawl, dictfetchall
# Create your views here.

def index(request):
  login_session = request.session.get('login_session', '')

  cursor = connection.cursor()
  sqlRank = "SELECT RECIPE_NM, count(RECIPE_NM) as count from th_search1 group by RECIPE_NM having count(RECIPE_NM) > 1 order by 2 desc limit 5;"

  cursor.execute(sqlRank)
  result_rank = dictfetchall(cursor)
  connection.close()

  rm = pd.DataFrame(result_rank, columns=['RECIPE_NM', 'rangking'])
  rank_all = rm.T.to_dict()

  return render(request, 'main/index.html', {"login_session" : login_session, "rank_all":rank_all})

@csrf_exempt
def second(request):
  #stt변수에 POST방식으로 'stt' 값을 전달 받는다. GET과 POST를 알아야한다.
  login_session = request.session.get('login_session', '')
  stt = request.POST.get('stt','')
  # print("111", stt)  #이 프린트는 딜레이해결 완료 할때까지 잠시 대기입니다.
  stt_edit = stt.replace(' ',"%")
  cursor = connection.cursor()
  recipeSql = "select recipe_nm from tb_recipe where recipe_nm like '"+ stt_edit + "' limit 1;"
  cursor.execute(recipeSql)
  recipeRst = cursor.fetchall()
  
  if recipeRst:
    recipe_nm = recipeRst[0][0]
    strSql = "select tb_irdent.GD_TYPE_CD, IRDNT_NM, GD_NM, GD_NUM, GD_ENT_NM "\
            + "from tb_recipe join tb_irdent on tb_recipe.RECIPE_NUM = tb_irdent.RECIPE_NUM join tb_gds on tb_irdent.GD_TYPE_CD = tb_gds.GD_TYPE_CD "\
            + "where RECIPE_NM like '"+ recipe_nm + "' order by rand();"

    cursor.execute(strSql)
    result = cursor.fetchall()
    connection.close()
    df = pd.DataFrame(result,columns=['gd_type_cd', 'irdnt_nm', 'gd_nm', 'gd_num', 'gd_ent_nm'])
    irdent = df.drop_duplicates(['gd_type_cd']).sort_values('gd_type_cd')
    irdent_dict = irdent.T.to_dict()
  else:
    irdent_dict = ""
    recipe_nm = stt

  return render(request, 'main/second.html',{"irdent_dict":irdent_dict, "login_session":login_session, "recipe_nm":recipe_nm})

@csrf_exempt
def third(request):
  login_session = request.session.get('login_session', '')
  lon = request.POST.get("lon")
  lat = request.POST.get("lat")
  cursor = connection.cursor()
  sqlMap = "select ent_num, ent_nm, map_y, map_x,ent_phone,ent_addr, dense_rank() over (order by ST_DISTANCE_SPHERE(POINT("+lon+", "+lat+"), POINT(MAP_Y, MAP_X))) as ranking from tb_ent limit 3;"

  cursor.execute(sqlMap)
  result_map = dictfetchall(cursor)
  connection.close()

  ent = [i["ent_num"] for i in result_map ]
  ent_nm = [i["ent_nm"] for i in result_map]
  
  irdent = request.POST.get("irdent")
  checked = request.POST.get('checked')
  irdent = eval(irdent)
  checked = checked.split()
  
  df = pd.DataFrame(irdent).T
  df = df[df["gd_num"].isin(list(map(int,checked)))]

  recipe_name =  request.POST.get('recipe')
  today = DateFormat(datetime.now()).format('Ymd')
  
  TBsearch = ThSearch1(user_id=login_session, recipe_nm=recipe_name, ht_date=today)
  TBsearch.save()
  search_id = TBsearch.id
  for row in df.itertuples():
    TBsearch = ThSearch2(search_id=search_id, irdnt_nm=row[2], gd_nm=row[3])
    TBsearch.save()
  
  good = df['gd_num'].tolist()
  
  print("api 동작")
  cost = crawl(good, ent)
  print("api 동작완료")
  
  df2 = pd.DataFrame(cost).T
  df2 = df2.reset_index()
  df2 = df2.rename(columns={'index':'gd_num'})

  merdf = pd.merge(df, df2, how='outer').fillna(0)
  
  # 소숫점 format
  merdf[['mart1', 'mart2', 'mart3']] = merdf[['mart1', 'mart2', 'mart3']].astype(int)
  for i, j in enumerate(result_map):
    j['mart'] = format(int(merdf['mart'+str(i+1)].sum()), ',')
  
  merdf = merdf.replace(0,"미제공")
  irdent_all = merdf.T.to_dict()

  dentJson = json.dumps(result_map, ensure_ascii=False)
  
  result_map.reverse()
  
  return render(request, 'main/third.html',{"ent_list":dentJson, 'irdent_all':irdent_all, 'map_list':result_map, 'ent_nm':ent_nm, "login_session":login_session,"lon":lon,"lat":lat}) 

server_dev/templates/main/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Mashead header-->
<div class="gold-113">
  <div class="row px-5 py-5" style="height: calc(96vh - 19px); width: 100%; ">
    <div class="row gx-5 align-items-center">
      <div class="col-lg-7">
        <!-- Mashead text and app badges-->
        <div class="mb-5 mb-lg-0" style="float:right;">
          <img src="{% static '/assets/img/title.png' %}" style="width: 650px; height: auto; max-width: 100%; padding-right:50px;"/>
        </div>
      </div>
      <!--이 아래는 음성인식하는 Web STT 부분 입니다.-->
      <div class="col-lg-5">
        <div>
          <div class="button" id="circlein" style="text-align: center">
            <div class="words" style="height: 40px"></div>
            <!--POST방식으로 이름을 stt로 받고 action은 우리가 보내려고하는 세컨드 페이지로 보낸다.-->
            <form method="post" name="stt" action="{% url 'main:second' %}">
                <!--타입은 히든으로 안 보여준다.-->
                <input type="hidden" name="stt" id="stt" class="stt" name="sttname"/>
            </form>
            <i class="fa-solid fa-microphone-lines fa-border fa-5x"></i>
          </div>
        </div>
        <div class="gold-57">
        {% for rank in rank_all.values %}
          <div class="gold-56">
            # {{ rank.RECIPE_NM }}
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block script %}

<script
  src="https://kit.fontawesome.com/4f4953a7c7.js"
  crossorigin="anonymous"
></script>
<script>
  window.SpeechRecognition =
    window.SpeechRecognition || window.webkitSpeechRecognition;

  // 인스턴스 생성
  const recognition = new SpeechRecognition();

  // true면 음절을 연속적으로 인식하나 false면 한 음절만 기록함
  recognition.interimResults = false;
  // 값이 없으면 HTML의 <html lang="en">을 참고합니다. ko-KR, en-US
  recognition.lang = "ko-KR";
  // true means continuous, and false means not continuous (single result each time.)
  // true면 음성 인식이 안 끝나고 계속 됩니다.
  recognition.continuous = false;
  // 숫자가 작을수록 발음대로 적고, 크면 문장의 적합도에 따라 알맞은 단어로 대체합니다.
  // maxAlternatives가 크면 이상한 단어도 문장에 적합하게 알아서 수정합니다.
  recognition.maxAlternatives = 10000;

  let p = document.createElement("p");
  p.classList.add("para");

  let words = document.querySelector(".words");
  words.appendChild(p);

  let mic = document.querySelector("#circlein");

  let speechToText = "";
  recognition.addEventListener("result", (e) => {
    let interimTranscript = "";
    for (let i = e.resultIndex, len = e.results.length; i < len; i++) {
      let transcript = e.results[i][0].transcript;
      console.log(transcript);
      if (e.results[i].isFinal) {
        speechToText += transcript;
      } else {
        interimTranscript += transcript;
      }
    }
    document.querySelector(".para").innerHTML =
      speechToText + interimTranscript;

    //이 부분은 second페이지로 넘겨주기 위한 'stt' 변수에 사용자가 말한 값을 넣어서 stt를 찾음
    document.querySelector(".stt").value = speechToText + interimTranscript;
    //따로 버튼을 누르지 않아도 자동으로 서버에 값이 제출되게 하여 페이지가 넘어갑니다.
    document.stt.submit()
  });

  // 음성인식이 끝나면 자동으로 재시작합니다.
  // recognition.addEventListener("end", recognition.start);

  // 음성 인식 시작
  mic.addEventListener("click", () => {
    recognition.start();

    // mic.style.backgroundColor = "#000000"
  });
</script>
{% endblock %}

server_dev/templates/main/second.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Header-->
<header class="p-5" style="background-color : #FFCC66;">
    <div class="container px-5 px-lg-5 my-5 mt-10">
        <div class="text-center text-white"style="width:center; height:center;" >
            <br><br><br>
            {% if irdent_dict %}
                <h1 class="display-4 fw-bolder b-1" >체크 상품을 담으시겠습니까?</h1>
                <p class="lead fw-normal b-2" style="width:center;">"{{ recipe_nm }}"</p>
            {% else %}
                <h1 class="display-4 fw-bolder b-1" >찾으시는 메뉴가 없습니다.</h1>
                <p class="lead fw-normal b-2" style="width:center;">"{{ recipe_nm }}"</p>
            {% endif %}
        </div>
    </div>
</header>

<div class="py-4">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row row-cols-2 row-cols-md-4 row-cols-xl-5 justify-content-center">
            {% for value in irdent_dict.values %}
                <div class="card text-center">
                    <img class="card-body" src="{% get_static_prefix %}images/IMAGE/{{ value.gd_nm }}.jpg" width="230px" height="200px">
                    {{ value.gd_nm }}
                    <div class="text-center">
                        <input type="checkbox" name="selected" id="selected" value="{{ value.gd_num }}" style="width:30px; height:30px; accent-color: #FF5E05;" checked>
                    </div> 
                </div>   
            {% endfor %}
        </div>
    </div>
</div>
<form id="sendForm" method="POST" action="{% url 'main:third' %}" >
    <div id="test_view">
        <input type="hidden" id="irdent" name="irdent" value="{{ irdent_dict }}">
        <input type="hidden" id="checked" name="checked" value="">
        <input type="hidden" id="lon", name="lon" value=""> 
        <input type="hidden" id="lat", name="lat" value="">
        <input type="hidden" id="recipe" name="recipe" value="{{ recipe_nm }}">
    </div>
    <div style="text-align:center; margin:50px;">
        {% if irdent_dict %}
            <button type="submit" onclick="getValue()">다음으로</button>
        {% else %}
            <button type="button" onclick="location.href='{% url 'main:index' %}'" >이전으로</button>
        {% endif %}
    </div>
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
    navigator.geolocation.getCurrentPosition(geoSuccess, getError);
    function geoSuccess(position) {
        var lat = position.coords.latitude;
        var lon = position.coords.longitude;
        document.getElementById('lon').value = lon
        document.getElementById('lat').value = lat
    }
    function getError() {
        alert('Geolocation Error')
    }
    function getValue()  {
        // 선택된 목록 가져오기
        const query = 'input[name="selected"]:checked';
        const selectedEls = 
            document.querySelectorAll(query);
        
        // 선택된 목록에서 value 찾기
        let result = '';
        selectedEls.forEach((el) => {
          result += el.value + ' ';
        });

        document.getElementById('checked').value = result
        document.getElementById('recipe')
        document.getElementById('sendForm').submit();
    }
</script>
{% endblock %}

server_dev/templates/main/stt.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Speech Application</title>
    <link rel="stylesheet" href="style.css">

</head>

<body>

    <div class="words"></div>

    <div class="obj">
        <div class="button" id="circlein">
            <svg class="mic-icon" version="1.1"
                 x="0px" y="0px" viewBox="0 0 3000 3000"
                style="fill:#1E2D70">
            </svg>
        </div>
    </div>

    <script src="../../static/js/app.js"></script>
</body>

</html>

server_dev/templates/main/test.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>여러개 마커 표시하기</title>
    
</head>
<body>
<div id="map" style="width:100%;height:350px;"></div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=발급받은 APP KEY를 사용하세요"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div  
    mapOption = { 
        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };

var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다
 
// 마커를 표시할 위치와 title 객체 배열입니다 
var positions = [
    {
        title: '카카오', 
        latlng: new kakao.maps.LatLng(33.450705, 126.570677)
    },
    {
        title: '생태연못', 
        latlng: new kakao.maps.LatLng(33.450936, 126.569477)
    },
    {
        title: '텃밭', 
        latlng: new kakao.maps.LatLng(33.450879, 126.569940)
    },
    {
        title: '근린공원',
        latlng: new kakao.maps.LatLng(33.451393, 126.570738)
    }
];

// 마커 이미지의 이미지 주소입니다
var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png"; 
    
for (var i = 0; i < positions.length; i ++) {
    
    // 마커 이미지의 이미지 크기 입니다
    var imageSize = new kakao.maps.Size(24, 35); 
    
    // 마커 이미지를 생성합니다    
    var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize); 
    
    // 마커를 생성합니다
    var marker = new kakao.maps.Marker({
        map: map, // 마커를 표시할 지도
        position: positions[i].latlng, // 마커를 표시할 위치
        title : positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
        image : markerImage // 마커 이미지 
    });
}
</script>
</body>
</html>